import math
from pyglet.window import key
from pyglet import sprite, image
from . import physycalobjects, resources, weapons

class Player (physycalobjects.PhysycalObjects):
    """
    Class defining player sprite and behaviour, user imput.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(img=resources.player_image, *args, **kwargs)

        #Set up player engine flame sprite
        self.engine_sprite = sprite.Sprite(img=resources.engine_flame_image, *args, **kwargs)
        self.engine_sprite.scale = 1.5
        self.engine_sprite.visible = False

        #Set up reaction to laser
        self.react_to_laser = False

        # Constants
        self.thrust = 100
        self.rotate_speed = 100
        self.laser_speed = 500

        #Game starts to recognise key handlers
        self.key_handler = key.KeyStateHandler()
        self.event_handlers = [self, self.key_handler]

    def update(self, dt):
        super ().update(dt)

        """
        Updating player sprite position based on user keyboard imputs.
        """
        if self.key_handler[key.LEFT] or self.key_handler[key.A]:
            self.rotation += -self.rotate_speed * dt
        if self.key_handler[key.RIGHT] or self.key_handler[key.D]:
            self.rotation += +self.rotate_speed * dt
        if self.key_handler[key.DOWN]  or self.key_handler[key.S]:
            #Change of angle based on imput
            angle_in_rad = math.radians(self.rotation)
            #Speed increment generated by user imput
            speed_increment_x = math.sin(angle_in_rad) * self.thrust * dt
            speed_increment_y = math.cos(angle_in_rad) * self.thrust * dt
            #Update actual speed
            self.speed_x -= speed_increment_x
            self.speed_y -= speed_increment_y
        if self.key_handler[key.UP] or self.key_handler[key.W]:
            #Change of angle based on imput
            angle_in_rad = math.radians(self.rotation)
            #Speed increment generated by user imput
            speed_increment_x = math.sin(angle_in_rad) * self.thrust * dt
            speed_increment_y = math.cos(angle_in_rad) * self.thrust * dt
            #Update actual speed
            self.speed_x += speed_increment_x
            self.speed_y += speed_increment_y
            #Update position of player engine sprite; only active when thrusting forward
            self.engine_sprite.rotation = self.rotation
            self.engine_sprite.x = self.x
            self.engine_sprite.y = self.y  
            #Set up engine flame
            self.engine_sprite.visible = True      
        else:
            self.engine_sprite.visible = False

    def on_key_press (self, symbol, modifiers):
        if symbol == key.SPACE:
            self.fire()          

    def fire(self):
        """
        Fires laser from player ship.
        """
        #Change is same as player ship
        angle_in_rad = math.radians(self.rotation)
        #Set up ship radius 
        ship_radius = self.image.width / 2
        #Laser position based on player ship position
        laser_x = self.x + math.sin(angle_in_rad) * ship_radius
        laser_y = self.y + math.cos(angle_in_rad) * ship_radius
        #Create instance of laser object
        new_laser = weapons.Laser(laser_x, laser_y, batch=self.batch)
        #Set up laser speed based on player speed and laser constant speed
        laser_speed_x = self.speed_x + math.sin(angle_in_rad) * self.laser_speed
        laser_speed_y = self.speed_y + math.cos(angle_in_rad) * self.laser_speed
        new_laser.speed_x = laser_speed_x
        new_laser.speed_y = laser_speed_y
        #Set up rotation based on initial rotation of players ship
        new_laser.rotation = self.rotation
        #Add laser instance to list of new objects
        self.new_objects.append(new_laser)


    def delete(self):
        """
        Delete the player instance and player engine sprite
        """
        self.engine_sprite.delete()
        super(Player, self).delete()